SEED_ROWS = [
    {
        "text": "We use encryption to protect your personal information during transmission and storage.",
        "label": 0,
        "source": "seed",
        "category": "security",
        "document": "seed-low",
    },
    {
        "text": "You may request access to your data and ask us to correct inaccurate personal information.",
        "label": 0,
        "source": "seed",
        "category": "user rights",
        "document": "seed-low",
    },
    {
        "text": "You can delete your account and request deletion of your personal data at any time.",
        "label": 0,
        "source": "seed",
        "category": "user rights",
        "document": "seed-low",
    },
    {
        "text": "We do not sell your personal information to advertisers or unrelated third parties.",
        "label": 0,
        "source": "seed",
        "category": "data sale",
        "document": "seed-low",
    },
    {
        "text": "We collect only the information needed to provide the service and follow data minimization practices.",
        "label": 0,
        "source": "seed",
        "category": "data minimization",
        "document": "seed-low",
    },
    {
        "text": "You may opt out of marketing emails by using the unsubscribe link in each email.",
        "label": 0,
        "source": "seed",
        "category": "marketing",
        "document": "seed-low",
    },
    {
        "text": "We allow you to withdraw consent for optional processing through your privacy settings.",
        "label": 0,
        "source": "seed",
        "category": "consent",
        "document": "seed-low",
    },
    {
        "text": "Personal data is retained only for as long as necessary for the stated purpose.",
        "label": 0,
        "source": "seed",
        "category": "retention",
        "document": "seed-low",
    },
    {
        "text": "We provide privacy controls so you can manage cookies and advertising preferences.",
        "label": 0,
        "source": "seed",
        "category": "privacy controls",
        "document": "seed-low",
    },
    {
        "text": "The service supports two-factor authentication to help keep your account secure.",
        "label": 0,
        "source": "seed",
        "category": "security",
        "document": "seed-low",
    },
    {
        "text": "We may use cookies to remember your preferences and improve website performance.",
        "label": 1,
        "source": "seed",
        "category": "cookies",
        "document": "seed-medium",
    },
    {
        "text": "We collect usage data such as pages viewed, clicks, and session duration for analytics.",
        "label": 1,
        "source": "seed",
        "category": "analytics",
        "document": "seed-medium",
    },
    {
        "text": "We may share information with service providers who help us operate the platform.",
        "label": 1,
        "source": "seed",
        "category": "service providers",
        "document": "seed-medium",
    },
    {
        "text": "We may collect your IP address, browser type, and device information when you use the service.",
        "label": 1,
        "source": "seed",
        "category": "device data",
        "document": "seed-medium",
    },
    {
        "text": "We use analytics tools to understand user behavior and improve our products.",
        "label": 1,
        "source": "seed",
        "category": "analytics",
        "document": "seed-medium",
    },
    {
        "text": "We may send marketing communications about new features unless you opt out.",
        "label": 1,
        "source": "seed",
        "category": "marketing",
        "document": "seed-medium",
    },
    {
        "text": "Third-party integrations may process limited account information to provide connected features.",
        "label": 1,
        "source": "seed",
        "category": "third party",
        "document": "seed-medium",
    },
    {
        "text": "We may retain your information to comply with legal requirements and resolve disputes.",
        "label": 1,
        "source": "seed",
        "category": "retention",
        "document": "seed-medium",
    },
    {
        "text": "Advertising partners may receive limited technical identifiers to measure campaign performance.",
        "label": 1,
        "source": "seed",
        "category": "advertising",
        "document": "seed-medium",
    },
    {
        "text": "We may process approximate location information based on your IP address.",
        "label": 1,
        "source": "seed",
        "category": "location",
        "document": "seed-medium",
    },
    {
        "text": "We may sell your personal information to advertising partners for targeted marketing.",
        "label": 2,
        "source": "seed",
        "category": "data sale",
        "document": "seed-high",
    },
    {
        "text": "By using the service, you waive your right to participate in any class action lawsuit.",
        "label": 2,
        "source": "seed",
        "category": "rights waiver",
        "document": "seed-high",
    },
    {
        "text": "All disputes must be resolved through binding arbitration and not in court.",
        "label": 2,
        "source": "seed",
        "category": "arbitration",
        "document": "seed-high",
    },
    {
        "text": "We are not liable for loss of data, lost profits, or damages arising from your use of the service.",
        "label": 2,
        "source": "seed",
        "category": "liability",
        "document": "seed-high",
    },
    {
        "text": "You grant us an irrevocable, perpetual, worldwide license to use your uploaded content.",
        "label": 2,
        "source": "seed",
        "category": "content license",
        "document": "seed-high",
    },
    {
        "text": "We may change these terms at any time without notice to you.",
        "label": 2,
        "source": "seed",
        "category": "terms change",
        "document": "seed-high",
    },
    {
        "text": "We may terminate your account at any time at our sole discretion without explanation.",
        "label": 2,
        "source": "seed",
        "category": "termination",
        "document": "seed-high",
    },
    {
        "text": "We may collect precise location data even when the application is running in the background.",
        "label": 2,
        "source": "seed",
        "category": "location",
        "document": "seed-high",
    },
    {
        "text": "We may share sensitive personal information with third parties for marketing purposes.",
        "label": 2,
        "source": "seed",
        "category": "sensitive data",
        "document": "seed-high",
    },
    {
        "text": "Employees may be required to work for 16 hours a day during peak business periods.",
        "label": 2,
        "source": "seed",
        "category": "labor risk",
        "document": "seed-high",
    },
]
